### ISSUE TITLE
Change the positiion fab menu

### ISSUE THREAD

**Issue by Mario21145** [DisGabriele/Garage#2]
### **_You can change the position of the fab menu by aligning it in the bottom left corner_** 

![Screenshot 2024-01-26 142809](https://github.com/DisGabriele/Garage/assets/144329270/0b181c6d-2c0e-4416-9212-8ff8dcca2831)

**Comment by DisGabriele** [comment]
the Float button position has been moved to the left. Thanks for your feedback
