### ISSUE TITLE
Top margin of the placeholder image , color name application

### ISSUE THREAD

**Issue by Mario21145** [DisGabriele/Garage#3]
The top margin is too cloose when the image placeholder is showed

Also the color of the app name is black is bettere if it is with white

![Screenshot 2024-01-26 143705](https://github.com/DisGabriele/Garage/assets/144329270/fd3859fb-a836-4a51-b3f6-94c354ffb4ad)

**Comment by DisGabriele** [comment]
the issue has been resolved (top bar color has been changed to white and the icon has been adjusted). Thanks for feedback
